kind: pipeline
name: default

steps:
  - name: tests
    image: node:12.14.0-alpine3.11
    environment:
      POSTGRESQL_HOST: database
      POSTGRESQL_DB: snipsnap-test
      NODE_ENV: test
    commands:
      - npm install
      - npm run lint
      - npm run db:create
      - npm run db:migrate
      - npm run test

services:
  - name: database
    image: postgres:12.1
